### ISSUE TITLE
Is the rejection and adjusting probability implementation different from normal speculative sampling?

### ISSUE THREAD

**Issue by AlvL1225** [SafeAILab/EAGLE#20]
<img width="594" alt="image" src="https://github.com/SafeAILab/EAGLE/assets/36012554/3984eebe-4be1-47cb-8b38-0fca650c5b7e">

However, in other implementations: like GPT-fast, or lucidrains implementation, the probability (GTP - Q )should be subtracted elementwisely but not only the rejected element?
<img width="497" alt="image" src="https://github.com/SafeAILab/EAGLE/assets/36012554/f91085eb-73d1-4054-8af4-ca66682f1ce4">

**Comment by Liyuhui-12** [comment]
Thanks! The correct approach should be to subtract the two distributions rather than adjust the value of the rejected elements. We have already adjusted the non-greedy code. Since sampling without replacement is performed here, a mask is used to adjust the draft distribution. The rest is consistent with the code in the screenshot you provided.
![image](https://github.com/SafeAILab/EAGLE/assets/81251885/8396c148-d74a-4d61-9f35-fcf520ca2550)


All the experimental results we provided were under the greedy decoding setting and are not affected.
